# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aeQLkaAAyACkD1OBN8rnw9ZoMHi2nmod
"""

import streamlit as st
from transformers import pipeline

# Page title and initial setup
st.set_page_config(page_title="Fast Text Summarizer", layout="centered")

st.title("⚡ Fast Text Summarizer")

st.markdown("""
Welcome to the Fast Text Summarizer app!
Paste your **English** text below, and get a quick summary using a lightweight model.
""")

# --- Input Section ---
st.header("Input Text")
st.info("Paste the text you want to summarize here.")

text = st.text_area("Your Text:", height=250, label_visibility="collapsed") # Use collapsed label for cleaner look

# Load faster English summarizer model
@st.cache_resource
def load_model():
    return pipeline("summarization", model="sshleifer/distilbart-cnn-12-6")

summarizer = load_model()

# Summarize button
if st.button("Summarize Text"):
    if text.strip():
        # --- Output Section ---
        st.header("Generated Summary")
        try:
            # Adjust max_length and min_length as needed for English text
            with st.spinner("Generating summary..."): # Add a spinner while processing
                 summary = summarizer(text, max_length=150, min_length=40, do_sample=False)[0]['summary_text']
            st.success(summary)
        except Exception as e:
            st.error(f"An error occurred during summarization: {e}")
            st.warning("Summarization might fail for very long texts or non-English input.")
    else:
        st.warning("Please enter some text to summarize!")

st.markdown("---")
st.markdown("App powered by Streamlit and Hugging Face Transformers.")



